services:
  - type: web
    name: ttsh-hackathon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash release.sh && gunicorn ttsh.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ttsh.settings
      - key: PYTHON_VERSION
        value: 3.13.4