services:
  - type: web
    name: ttsh-hackathon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./release.sh && gunicorn ttsh.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ttsh.settings
      - key: PYTHON_VERSION
        value: 3.13.4